# Generated by Django 4.2.11 on 2024-05-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postlike_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
