# Generated by Django 4.2.11 on 2024-05-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postlike_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='post',
            new_name='comment',
        ),
    ]
