# Generated by Django 4.2.11 on 2024-05-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_post_commentlike_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='like',
            field=models.IntegerField(),
        ),
    ]
